package br.gov.caixa.sigct.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2018-09-27T13:57:07.641-03:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://client.sigct.caixa.gov.br/", name = "SigctService")
@XmlSeeAlso({ObjectFactory.class})
public interface SigctService {

    @WebMethod
    @RequestWrapper(localName = "getTermosAlterados", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetTermosAlterados")
    @ResponseWrapper(localName = "getTermosAlteradosResponse", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetTermosAlteradosResponse")
    @WebResult(name = "Termo", targetNamespace = "")
    public java.util.List<br.gov.caixa.sigct.client.TermosView> getTermosAlterados(
        @WebParam(name = "Login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "Senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "Contrato", targetNamespace = "")
        java.lang.Long contrato,
        @WebParam(name = "Site", targetNamespace = "")
        java.lang.String site
    ) throws SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getContratacoesAlteradas", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoesAlteradas")
    @ResponseWrapper(localName = "getContratacoesAlteradasResponse", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoesAlteradasResponse")
    @WebResult(name = "Contratacao", targetNamespace = "")
    public java.util.List<br.gov.caixa.sigct.client.ContratacoesView> getContratacoesAlteradas(
        @WebParam(name = "Login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "Senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "Contrato", targetNamespace = "")
        java.lang.Long contrato,
        @WebParam(name = "Site", targetNamespace = "")
        java.lang.String site
    ) throws SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getContratacoes", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoes")
    @ResponseWrapper(localName = "getContratacoesResponse", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoesResponse")
    @WebResult(name = "Contratacao", targetNamespace = "")
    public java.util.List<br.gov.caixa.sigct.client.ContratacoesView> getContratacoes(
        @WebParam(name = "Login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "Senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "Contrato", targetNamespace = "")
        java.lang.Long contrato,
        @WebParam(name = "Site", targetNamespace = "")
        java.lang.String site,
        @WebParam(name = "Pagina", targetNamespace = "")
        java.lang.Integer pagina
    ) throws SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getContratacoesFaturamentoAtual", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoesFaturamentoAtual")
    @ResponseWrapper(localName = "getContratacoesFaturamentoAtualResponse", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetContratacoesFaturamentoAtualResponse")
    @WebResult(name = "Contratacao", targetNamespace = "")
    public java.util.List<br.gov.caixa.sigct.client.ContratacoesView> getContratacoesFaturamentoAtual(
        @WebParam(name = "Login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "Senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "Contrato", targetNamespace = "")
        java.lang.Long contrato,
        @WebParam(name = "Site", targetNamespace = "")
        java.lang.String site
    ) throws SOAPException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getTermos", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetTermos")
    @ResponseWrapper(localName = "getTermosResponse", targetNamespace = "http://client.sigct.caixa.gov.br/", className = "br.gov.caixa.sigct.client.GetTermosResponse")
    @WebResult(name = "Termo", targetNamespace = "")
    public java.util.List<br.gov.caixa.sigct.client.TermosView> getTermos(
        @WebParam(name = "Login", targetNamespace = "")
        java.lang.String login,
        @WebParam(name = "Senha", targetNamespace = "")
        java.lang.String senha,
        @WebParam(name = "Contrato", targetNamespace = "")
        java.lang.Long contrato,
        @WebParam(name = "Site", targetNamespace = "")
        java.lang.String site,
        @WebParam(name = "Fatura", targetNamespace = "")
        java.lang.String fatura
    ) throws SOAPException_Exception;
}
